version: '3.3'

services:
    monitoring:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/code
    
    web:
        build: web
        ports:
            - "8005:8084"
        volumes:
            - ./src:/etc/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf

