version: '3.3'

services:
  db:
    image: mysql
    #restart: always
    environment:
      MYSQL_DATABASE: 't-tracker'
      MYSQL_USER: 'useraroo'
      MYSQL_ROOT_PASSWORD: 'lepwd'
      MYSQL_PASSWORD: 'lepwd'
      MYSQL_TCP_PORT: 3307 # change default MYSQL port from 3306 to 3307
    ports:
      - '3307:3307' # -[port_outside_container]:[port_inside_container]
    volumes:
      - db-data:/var/lib/mysql # persist DB data, even after "docker-compose down"
    expose:
    # opens port 3307 on the container
      - '3307'
  
  backend-tracker:
    image: store-backend
    build:
      context: t-tracker
      dockerfile: Dockerfile
    ports:
      - "8081:8082"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/t-tracker
      SPRING_DATASOURCE_USERNAME: useraroo
      SPRING_DATASOURCE_PASSWORD: lepwd
      SPRING_RABBITMQ_HOST: lepwd
    depends_on: 
      - db
    networks:
      - default

  client:
    build: web
    ports:
      - "8001:8083"
    volumes:
      - ./src:/etc/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
        - backend-tracker

networks:
  default:
      external:
          name: rede
