version: '3.3'

services:
  db:
    image: mysql
    #restart: always
    environment:
      MYSQL_DATABASE: 't-tracker'
      MYSQL_USER: 'useraroo'
      MYSQL_ROOT_PASSWORD: 'lepwd'
      MYSQL_PASSWORD: 'lepwd'
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    #volumes:
      #- db-data1:/var/lib/mysql
      #- ./mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    expose:
    # opens port 3306 on the container
    - '3307'