version: '3.3'

services:
  db:
    image: mysql
    #restart: always
    environment:
      MYSQL_DATABASE: 'deliveries-engine'
      MYSQL_USER: 'useraroo'
      MYSQL_ROOT_PASSWORD: 'lepwd'
      MYSQL_PASSWORD: 'lepwd'
    ports:
      - '3306:3306'
    #volumes:
      #- db-data1:/var/lib/mysql
      #- ./mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    expose:
    # opens port 3306 on the container
      - '3306'
  
  backend:
    image: deli-eng-backend
    build:
      context: deliveries-engine
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/deliveries-engine
      SPRING_DATASOURCE_USERNAME: useraroo
      SPRING_DATASOURCE_PASSWORD: lepwd
      SPRING_RABBITMQ_HOST: lepwd
    depends_on: 
      - db

  #client:
  #  image: deli-eng-frontend
  #  build: ./web
  #  ports:
  #      - "8081:80"
  #  #volumes:
  #  #    - ./web:/etc/share/nginx/html
  #  #    - ./nginx.conf:/etc/nginx/nginx.conf
  #  depends_on: 
  #      - backend