version: '3.3'

services:
  db:
    image: mysql
    #restart: always
    environment:
      MYSQL_DATABASE: 'deliveries-engine'
      MYSQL_USER: 'useraroo'
      MYSQL_ROOT_PASSWORD: 'lepwd'
      MYSQL_PASSWORD: 'lepwd'
    ports:
      - '3306:3306' # -[port_outside_container]:[port_inside_container]
    volumes:
      - db-data:/var/lib/mysql # persist DB data, even after "docker-compose down"
    expose:
    # opens port 3306 on the container
      - '3306'
  
  backend-engine:
    build:
      context: deliveries-engine
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/deliveries-engine
      SPRING_DATASOURCE_USERNAME: useraroo
      SPRING_DATASOURCE_PASSWORD: lepwd
      SPRING_RABBITMQ_HOST: lepwd
    depends_on: 
      - db

  client:
    build: web
    ports:
      - "8002:8082"
    volumes:
      - ./src:/etc/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
        - backend-engine

networks:
  default:
    external:
      name: rede

volumes:
  db-data:
