name: Deliveries Engine Runner

on:
  # triggers the workflow on push for the deployment branch
  push:
    branches: [ deployment, workflows ]

  # triggers the workflow on pull requests for the deployment branch
  pull_request:
    branches: [ deployment ]

jobs:
  deployment:
    # the type of runner that the job will run on, in this case, it will be on the Github runner that is ruunning on the vm provided for this project
    runs-on:
    - deliveries-engine-runner

    name: Run deliveries-engine docker-compose
    steps:
    - uses: actions/checkout@v2
    - name: Run compose
      # when running the docker-compose, this actions won't be marked as finished because, while the service is running on the vm runner, the workflow won't finish
      run: |
        cd deliveries-engine/
        sudo docker-compose down
        sudo docker-compose up --build -d
