name: Monitoring Pipeline

# controls when the action will run
on:
  # triggers the workflow on push for the develop and deployment branches
  push:
    branches: [ deployment, ci-cd-monitoring ]
    paths-ignore:
      - 'reporting/**' # don't run this workflow when the are pushes, and there are only changes for this directory
      # don't run this workflow when the are pushes and there are only changes for the following files:
      - '**.md'
      - '**.pdf'
      - '**.docx'
      - '**.gitignore'

  # triggers the workflow on pull requests for the main branch
  pull_request:
    branches: [ deployment, ci-cd-monitoring ]
    paths-ignore:
      - 'reporting/**' # don't run this workflow when the are pull requests, and there are only changes for this directory
      # don't run this workflow when the are pull requests, and there are only changes for the following files:
      - '**.md'
      - '**.pdf'
      - '**.docx'
      - '**.gitignore'

  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  monitoring:
    # the type of runner that the job will run on, in this case, it will be on the Github runner that is ruunning on the vm provided for this project
    runs-on:
    - deliveries-engine-runner

    name: Deploy monitoring
    steps:
    - uses: actions/checkout@v2
    - name: Run compose
      run: |
        cd monitoring/
        sudo docker-compose down
        sudo docker-compose up --build -d