name: T-Tracker Runner

on:
  # triggers the workflow on push for the deployment branch
  push:
    branches: [ deployment ]

  # triggers the workflow on pull requests for the deployment branch
  pull_request:
    branches: [ deployment ]

jobs:
  t-tracker-runner:
    # the type of runner that the job will run on, in this case, it will be on the Github runner that is ruunning on the vm provided for this project
    runs-on:
    - t-tracker-runner

    name: Run t-tracker docker-compose
    steps:
    - uses: actions/checkout@v2
    - name: Run compose
      run: |
        cd t-tracker/
        sudo docker-compose down
        sudo docker-compose up --build -d

  db-migration:
    name: Migrate DB
    # the type of runner that the job will run on, in this case, it will be on the Github runner that is ruunning on the vm provided for this project
    runs-on: t-tracker-runner

    needs: [t-tracker-runner]

    # run this job only if the previous one succeeds, to prevent trying to migrate non-existent DB
    if: always() && needs.t-tracker-runner.result == 'success'

    # steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from Github
        uses: actions/checkout@v2

      - name: Step 2 - Have Flyway migrate the t-tracker project's database
        run: |
          cd t-tracker/t-tracker/
          mvn clean install -Dmaven.test.skip=true
          mvn clean flyway:migrate -Dflyway.configFiles=myFlywayConfig.properties